# set keyboard layouts
$template.xsession.setxkbmap$

# ~terminus~
xset +fp ~/fonts

# enable ctrl-alt-backspace sequence
setxkbmap -option terminate:ctrl_alt_bksp
# give up right alt key to xcompose
setxkbmap -option compose:ralt

# start kbdd
kbdd

# set the wallpaper
xsetroot -solid '#220000'

# set a non-nonsensical default cursor
xsetroot -cursor_name arrow

# process .xmodmap
xmodmap ~/.xmodmap

# start clipboard/primary selection synchronizer
parcellite &

# start pakej
sh -l -c pakej

# start unclutter
unclutter -idle 2 &

# start autolocker
xautolock -time 10 -locker slock &
