#!/usr/bin/env python

# convenience imports
from collections import *
from functools import *
from itertools import *
import datetime
import operator
import os
import re
import subprocess
import sys
import time

# make repl at least mildly usable
# note: all these modules will be removed from
# repl environment at the end of startup script
import readline
import rlcompleter
import atexit

def have_a_nice_day():
    print()
    print("Have a nice day.")

# registered functions are run in the reverse order
atexit.register(have_a_nice_day)

# initialize completion
readline.parse_and_bind("tab: complete")

# initialize history
history = os.path.join(os.environ['HOME'], ".pythonhist")
if os.path.isfile(history):
    readline.read_history_file(history)
atexit.register(readline.write_history_file, history)

del readline, rlcompleter, atexit
