# set keyboard layouts
setxkbmap -option "" -layout "us,ru" -option grp:caps_toggle -option grp_led:scroll :2

# ~terminus~
xset +fp ~/fonts

# enable ctrl-alt-backspace sequence
setxkbmap -option terminate:ctrl_alt_bksp
# enable right alt for xcompose
setxkbmap -option compose:ralt
# fix xcompose in gtk applications
export GTK_IM_MODULE=xim

# start kbdd
kbdd

# enable wallpaper
xsetroot -solid black

# process .xmodmap
xmodmap ~/.xmodmap

# start ssh-agent
ssh-agent
