# set keyboard layouts
setxkbmap -option "" -layout "us,ru" -option grp:caps_toggle -option grp_led:scroll :2

# ~terminus~
xset +fp ~/fonts

# enable ctrl-alt-backspace sequence
setxkbmap -option terminate:ctrl_alt_bksp
# enable right alt for xcompose
setxkbmap -option compose:ralt
# fix xcompose in gtk applications
export GTK_IM_MODULE=xim

# start kbdd
kbdd

# set wallpaper
xsetroot -solid black

# set non-nonsensical default cursor
xsetroot -cursor_name arrow

# process .xmodmap
xmodmap ~/.xmodmap

# start ssh-agent
ssh-agent

# start pakej
nohup sh -l -c 'pakej' 2>/dev/null 1>/dev/null &
