export GOROOT=${HOME}/go
export PYTHONSTARTUP=${HOME}/.pythonrc
export NIX_PATH="nix-rehash=https://github.com/supki/nix-rehash/archive/master.tar.gz:${NIX_PATH}"

export NO_SCRIPTS_NOTIFICATIONS=yes
export DEPLOY_DEFAULT_CMD=run

if [ -n "$NIX_GHC" ]; then
  NIX_GHCI=${NIX_GHC}i
fi
TERM=screen-256color
