function chpwd {
	print -Pn "\e]2;%~\a"
}

autoload -U compinit promptinit colors

fpath=(~/git/zsh-completions ~/git/zsh-cabal-completion $fpath)
compinit
setopt autocd correct
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

promptinit
colors
PROMPT="%F{blue}%n%f@%M:%F{yellow}%~%f%# "
PROMPT2="%F{blue}%_%f> "
RPROMPT="[%(?,%F{green}%?%f,%F{red}%?%f)]"

chpwd

HISTSIZE=1000
HISTFILE=~/.zhistory
SAVEHIST=1000
setopt sharehistory

setopt histignorealldups
setopt histignorespace

setopt autocd

bindkey -v
bindkey '^[[A' history-beginning-search-backward
bindkey '^[[B' history-beginning-search-forward
bindkey -a 'k' history-beginning-search-backward
bindkey -a 'j' history-beginning-search-forward
bindkey '^?' backward-delete-char
bindkey '^[[3~' delete-char
bindkey "^[[7~" beginning-of-line
bindkey "^[[8~" end-of-line

alias ack=ack-grep # stupid debian
alias ls='ls --color'
