" Appearance {
	" set gui font same as cli
	set guifont=Terminus\ 9
	" remove all unneded toolbars, menus and scrollbars
	set guioptions=
	" add X selection handle
	set guioptions+=a

	" enable mouse in normal and visual modes
	set mouse=nv
" }
